!classDefinition: #CartTest category: 'TusLibros-It3'!
TestCase subclass: #CartTest
	instanceVariableNames: 'testObjectFactory'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!CartTest methodsFor: 'tests'!
! !

!CartTest methodsFor: 'tests'!
! !

!CartTest methodsFor: 'tests'!
! !

!CartTest methodsFor: 'tests'!
! !

!CartTest methodsFor: 'tests'!
! !

!CartTest methodsFor: 'tests'!
! !

!CartTest methodsFor: 'tests'!
! !

!CartTest methodsFor: 'tests'!
! !


!CartTest methodsFor: 'assertions'!
! !


!classDefinition: #CheckoutTest category: 'TusLibros-It3'!
TestCase subclass: #CheckoutTest
	instanceVariableNames: 'testObjectFactory'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!CheckoutTest methodsFor: 'assertions'!
! !


!CheckoutTest methodsFor: 'tests'!
! !

!CheckoutTest methodsFor: 'tests'!
! !

!CheckoutTest methodsFor: 'tests'!
! !

!CheckoutTest methodsFor: 'tests'!
! !

!CheckoutTest methodsFor: 'tests'!
! !

!CheckoutTest methodsFor: 'tests'!
! !

!CheckoutTest methodsFor: 'tests'!
! !

!CheckoutTest methodsFor: 'tests'!
! !

!CheckoutTest methodsFor: 'tests'!
! !


!classDefinition: #TusLibrosSystemFacadeTest category: 'TusLibros-It3'!
TestCase subclass: #TusLibrosSystemFacadeTest
	instanceVariableNames: 'testObjectFactory'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!TusLibrosSystemFacadeTest methodsFor: 'as yet unclassified'!
! !

!TusLibrosSystemFacadeTest methodsFor: 'as yet unclassified'!
! !

!TusLibrosSystemFacadeTest methodsFor: 'as yet unclassified'!
! !

!TusLibrosSystemFacadeTest methodsFor: 'as yet unclassified'!
! !


!classDefinition: #AuthenticationSystem category: 'TusLibros-It3'!
Object subclass: #AuthenticationSystem
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!


!classDefinition: #SimulatedAuthSystem category: 'TusLibros-It3'!
AuthenticationSystem subclass: #SimulatedAuthSystem
	instanceVariableNames: 'errorDescription result'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!SimulatedAuthSystem methodsFor: 'initialization'!
! !

!SimulatedAuthSystem methodsFor: 'initialization'!
! !


!SimulatedAuthSystem methodsFor: 'as yet unclassified'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'SimulatedAuthSystem class' category: 'TusLibros-It3'!
SimulatedAuthSystem class
	instanceVariableNames: ''!

!SimulatedAuthSystem class methodsFor: 'instance creation'!
! !

!SimulatedAuthSystem class methodsFor: 'instance creation'!
! !


!classDefinition: #Card category: 'TusLibros-It3'!
Object subclass: #Card
	instanceVariableNames: 'expirationMonthOfYear number'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!Card methodsFor: 'accessing'!
! !


!Card methodsFor: 'initialization'!
! !


!Card methodsFor: 'testing'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Card class' category: 'TusLibros-It3'!
Card class
	instanceVariableNames: ''!

!Card class methodsFor: 'instance creation'!
! !


!classDefinition: #Cart category: 'TusLibros-It3'!
Object subclass: #Cart
	instanceVariableNames: 'contents catalog totalPrice'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!Cart methodsFor: 'accessing'!
! !

!Cart methodsFor: 'accessing'!
! !


!Cart methodsFor: 'adding'!
! !

!Cart methodsFor: 'adding'!
! !


!Cart methodsFor: 'assertions'!
! !

!Cart methodsFor: 'assertions'!
! !


!Cart methodsFor: 'initialization'!
! !


!Cart methodsFor: 'adding - private'!
! !


!Cart methodsFor: 'testing'!
! !

!Cart methodsFor: 'testing'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Cart class' category: 'TusLibros-It3'!
Cart class
	instanceVariableNames: ''!

!Cart class methodsFor: 'instance creation'!
! !


!Cart class methodsFor: 'error descriptions'!
! !

!Cart class methodsFor: 'error descriptions'!
! !


!classDefinition: #Cashier category: 'TusLibros-It3'!
Object subclass: #Cashier
	instanceVariableNames: 'merchantProcessor'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!Cashier methodsFor: 'assertions'!
! !

!Cashier methodsFor: 'assertions'!
! !

!Cashier methodsFor: 'assertions'!
! !

!Cashier methodsFor: 'assertions'!
! !


!Cashier methodsFor: 'checkout'!
! !


!Cashier methodsFor: 'initialization'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Cashier class' category: 'TusLibros-It3'!
Cashier class
	instanceVariableNames: ''!

!Cashier class methodsFor: 'error descriptions'!
! !

!Cashier class methodsFor: 'error descriptions'!
! !

!Cashier class methodsFor: 'error descriptions'!
! !


!Cashier class methodsFor: 'instance creation'!
! !


!classDefinition: #MerchantProcessor category: 'TusLibros-It3'!
Object subclass: #MerchantProcessor
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!MerchantProcessor methodsFor: 'as yet unclassified'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'MerchantProcessor class' category: 'TusLibros-It3'!
MerchantProcessor class
	instanceVariableNames: ''!

!MerchantProcessor class methodsFor: 'error descriptions'!
! !

!MerchantProcessor class methodsFor: 'error descriptions'!
! !


!classDefinition: #SimulatedMP category: 'TusLibros-It3'!
MerchantProcessor subclass: #SimulatedMP
	instanceVariableNames: 'noFundsCardNumber stolenCardNumber'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!SimulatedMP methodsFor: 'assertions'!
! !

!SimulatedMP methodsFor: 'assertions'!
! !

!SimulatedMP methodsFor: 'assertions'!
! !

!SimulatedMP methodsFor: 'assertions'!
! !


!SimulatedMP methodsFor: 'payment processing'!
! !


!SimulatedMP methodsFor: 'initialization'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'SimulatedMP class' category: 'TusLibros-It3'!
SimulatedMP class
	instanceVariableNames: 'noFundsCardNumber'!


!SimulatedMP class methodsFor: 'instance creation'!
! !


!classDefinition: #TestObjectFactory category: 'TusLibros-It3'!
Object subclass: #TestObjectFactory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!TestObjectFactory methodsFor: 'cards'!
! !

!TestObjectFactory methodsFor: 'cards'!
! !

!TestObjectFactory methodsFor: 'cards'!
! !

!TestObjectFactory methodsFor: 'cards'!
! !

!TestObjectFactory methodsFor: 'cards'!
! !

!TestObjectFactory methodsFor: 'cards'!
! !

!TestObjectFactory methodsFor: 'cards'!
! !


!TestObjectFactory methodsFor: 'dates'!
! !

!TestObjectFactory methodsFor: 'dates'!
! !

!TestObjectFactory methodsFor: 'dates'!
! !


!TestObjectFactory methodsFor: 'products'!
! !

!TestObjectFactory methodsFor: 'products'!
! !

!TestObjectFactory methodsFor: 'products'!
! !

!TestObjectFactory methodsFor: 'products'!
! !

!TestObjectFactory methodsFor: 'products'!
! !

!TestObjectFactory methodsFor: 'products'!
! !


!TestObjectFactory methodsFor: 'store creation'!
! !

!TestObjectFactory methodsFor: 'store creation'!
! !

!TestObjectFactory methodsFor: 'store creation'!
! !

!TestObjectFactory methodsFor: 'store creation'!
! !


!TestObjectFactory methodsFor: 'as yet unclassified'!
! !

!TestObjectFactory methodsFor: 'as yet unclassified'!
! !

!TestObjectFactory methodsFor: 'as yet unclassified'!
! !

!TestObjectFactory methodsFor: 'as yet unclassified'!
! !


!classDefinition: #TusLibrosSystemFacade category: 'TusLibros-It3'!
Object subclass: #TusLibrosSystemFacade
	instanceVariableNames: 'authenticationSystem'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibros-It3'!

!TusLibrosSystemFacade methodsFor: 'initialization'!
! !


!TusLibrosSystemFacade methodsFor: 'as yet unclassified'!
! !

!TusLibrosSystemFacade methodsFor: 'as yet unclassified'!
! !

!TusLibrosSystemFacade methodsFor: 'as yet unclassified'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'TusLibrosSystemFacade class' category: 'TusLibros-It3'!
TusLibrosSystemFacade class
	instanceVariableNames: ''!

!TusLibrosSystemFacade class methodsFor: 'instance creation'!
! !


!TusLibrosSystemFacade class methodsFor: 'error descriptions'!
! !
